# Generated by Django 4.0 on 2021-12-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='', verbose_name='Bild')),
                ('ingr', models.CharField(max_length=500)),
                ('instr', models.CharField(max_length=1000)),
            ],
        ),
    ]
