# Generated by Django 4.0 on 2021-12-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingr',
            field=models.TextField(max_length=500, verbose_name='Zutaten'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instr',
            field=models.TextField(max_length=1000, verbose_name='Anleitung'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
    ]
