# Generated by Django 4.0 on 2021-12-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0002_alter_recipe_ingr_alter_recipe_instr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instr',
            field=models.TextField(max_length=10000, verbose_name='Anleitung'),
        ),
    ]
