# Generated by Django 4.0.1 on 2022-01-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0004_alter_recipe_instr_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(to='buch.Category'),
        ),
    ]
