# Generated by Django 4.0.1 on 2022-01-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0005_category_recipe_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zutat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='buch.Zutat'),
        ),
    ]
