# Generated by Django 4.0.1 on 2022-01-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0006_zutat_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='kategorien',
            field=models.ManyToManyField(to='buch.Category'),
        ),
    ]
