# Generated by Django 4.0.1 on 2022-01-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0007_remove_recipe_categories_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.AddField(
            model_name='recipe',
            name='zutaten',
            field=models.ManyToManyField(to='buch.Zutat'),
        ),
    ]
