# Generated by Django 4.0.1 on 2022-01-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0008_remove_recipe_author_recipe_zutaten'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Author'),
        ),
    ]
