# Generated by Django 4.0.1 on 2022-01-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0009_recipe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='zutaten',
        ),
    ]
