# Generated by Django 4.0 on 2022-01-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0011_recipe_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
