# Generated by Django 4.0 on 2022-01-15 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buch', '0013_comment_delete_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comment',
            field=models.ManyToManyField(blank=True, related_query_name='comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
