# Generated by Django 4.0.1 on 2022-01-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0018_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favorites',
            new_name='favorite',
        ),
    ]
