# Generated by Django 4.0.1 on 2022-01-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0020_alter_profile_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/avatars/default-avatar.jpg', upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
