# Generated by Django 4.0.1 on 2022-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0023_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateProfileForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default-avatar.jpg', upload_to='avatars', verbose_name='Avatar')),
                ('bio', models.TextField(null=True)),
            ],
        ),
    ]
