# Generated by Django 4.0.1 on 2022-01-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0024_updateprofileform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateProfileForm',
        ),
    ]
