# Generated by Django 4.0.1 on 2022-01-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0026_tag_theme_recipe_tags_recipe_thema'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dauer',
            field=models.IntegerField(default='30', verbose_name='Dauer'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='schwierigkeit',
            field=models.CharField(choices=[('superleicht', 'Sehr leicht'), ('leicht', 'Leicht'), ('mittel', 'Mittel'), ('schwer', 'Schwer')], default='leicht', max_length=15),
        ),
        migrations.AddField(
            model_name='recipe',
            name='zutaten',
            field=models.ManyToManyField(to='buch.Zutat'),
        ),
    ]
