# Generated by Django 4.0.1 on 2022-01-23 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buch', '0027_recipe_dauer_recipe_schwierigkeit_recipe_zutaten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='zutaten',
        ),
        migrations.AddField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(related_name='rezepte', to=settings.AUTH_USER_MODEL),
        ),
    ]
