# Generated by Django 4.0.1 on 2022-01-23 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buch', '0028_remove_recipe_zutaten_recipe_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(null=True, related_name='rezepte', to=settings.AUTH_USER_MODEL),
        ),
    ]
