# Generated by Django 4.0.1 on 2022-01-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0029_alter_recipe_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comment',
        ),
        migrations.AddField(
            model_name='recipe',
            name='comment',
            field=models.TextField(max_length=300, null=True, verbose_name='Kommentar'),
        ),
    ]
