# Generated by Django 4.0.1 on 2022-01-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0030_remove_recipe_comment_recipe_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comment',
        ),
        migrations.AddField(
            model_name='recipe',
            name='comment',
            field=models.ManyToManyField(blank=True, related_query_name='comment', to='buch.Comment'),
        ),
    ]
