# Generated by Django 4.0.1 on 2022-01-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0031_remove_recipe_comment_recipe_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author'),
        ),
    ]
