# Generated by Django 4.0.1 on 2022-02-03 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buch', '0032_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_query_name='comment', to='buch.Comment'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='rezepte', to=settings.AUTH_USER_MODEL),
        ),
    ]
