# Generated by Django 4.0.1 on 2022-01-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0032_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='zutat',
            name='menge',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zutat',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zutaten', to='buch.recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zutat',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
