# Generated by Django 4.0.1 on 2022-01-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0033_zutat_menge_zutat_recipe_alter_zutat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zutat',
            name='menge',
            field=models.CharField(max_length=15),
        ),
    ]
