# Generated by Django 4.0.1 on 2022-01-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buch', '0034_alter_zutat_menge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zutat',
            name='menge',
        ),
        migrations.RemoveField(
            model_name='zutat',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_query_name='comment', to='buch.Comment'),
        ),
        migrations.AlterField(
            model_name='zutat',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
